# Generated by Django 3.1 on 2022-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220211_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_doctor',
            name='hospital',
            field=models.CharField(default='Teaching Hospital', max_length=50),
        ),
    ]
