# Generated by Django 3.1 on 2022-02-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_info_doctor_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_doctor',
            name='hospital',
            field=models.CharField(max_length=50),
        ),
    ]
