# Generated by Django 3.1.7 on 2021-03-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicalreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('report_location', models.CharField(max_length=500)),
                ('body_part', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='verify_pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('pin_no', models.IntegerField()),
            ],
        ),
    ]
