# Generated by Django 3.1 on 2022-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verify_pin',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='report_location',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='specification',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='doctor_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='pname',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_file',
            field=models.ImageField(default=None, upload_to='Patient'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_of',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='specifed_problem',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='hospital_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
