# Generated by Django 3.1 on 2022-02-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
