# Generated by Django 3.1 on 2022-02-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220211_0313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_info',
        ),
    ]
